### ISSUE TITLE
Windows incompatibility

### ISSUE THREAD

**Issue by basilveerman** [toumorokoshi/vcver-python#2]
Looks like it's due to this line: https://github.com/toumorokoshi/vcver-python/blob/3d1360e1b0dc7fbe9204c0730f93ce9dfa7c1139/vcver/scm/git.py#L9. Affects people who install packages in a conda/command prompt shell.

**Comment by toumorokoshi** [comment]
Hey Basil! Do you have more details on the error message you get, or what the specific nature of the issue is?

off the top of my head, I would assume the pipe character is causing issues here.

**Comment by basilveerman** [comment]
Sorry, had limited time before. Full stacktrace:
```
    ERROR: Command errored out with exit status 1:
     command: 'C:\Miniconda2\envs\geo\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\basilv\\appdata\\local\\temp\\pip-req-build-pxyt2i\\setup.py'"'"'; __file__='"'"'c:\\users\\basilv\\appdata\\local\\temp\\pip-req-build-pxyt2i\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\setup.py", line 54, in <module>
        test_suite="nose.collector"
      File "C:\Miniconda2\envs\geo\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Miniconda2\envs\geo\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Miniconda2\envs\geo\lib\site-packages\setuptools\dist.py", line 444, in __init__
        k: v for k, v in attrs.items()
      File "C:\Miniconda2\envs\geo\lib\distutils\dist.py", line 287, in __init__
        self.finalize_options()
      File "C:\Miniconda2\envs\geo\lib\site-packages\setuptools\dist.py", line 732, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\.eggs\vcver-0.2.0-py2.7.egg\vcver\__init__.py", line 9, in setup_keywords_entry_point
        version = get_version(**value)
      File "c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\.eggs\vcver-0.2.0-py2.7.egg\vcver\version.py", line 47, in get_version
        is_release=is_release,
      File "c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\.eggs\vcver-0.2.0-py2.7.egg\vcver\version.py", line 61, in determine_version
        props = scm.get_properties()
      File "c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\.eggs\vcver-0.2.0-py2.7.egg\vcver\scm\git.py", line 46, in get_properties
        tag, tag_version = self.get_latest_version_tag()
      File "c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\.eggs\vcver-0.2.0-py2.7.egg\vcver\scm\git.py", line 78, in get_latest_version_tag
        commit = self._cmd(CMD_FIRST_COMMIT)
      File "c:\users\basilv\appdata\local\temp\pip-req-build-pxyt2i\.eggs\vcver-0.2.0-py2.7.egg\vcver\scm\git.py", line 105, in _cmd
        "'{0}' returned an error code {1}".format(cmd, proc.returncode)
    vcver.scm.git.GitCommandError: 'git rev-list HEAD | tail -n 1' returned an error code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The error happens in both a conda prompt and windows command prompt.

I don't work in windows enough to nail down the exact issue, but it appears to be issues with the pipe and/or `tail`. Installing tail with [Windows Server 2003 Resource Kit Tools](https://www.microsoft.com/en-us/download/confirmation.aspx?id=17657) does not fix the issue.

```
(geo) C:\Users\basilv\code\gis-lib>git rev-list HEAD | head -n1
15d0fb0ab91f31125f065e6e35bd1b370e490f13

(geo) C:\Users\basilv\code\gis-lib>git rev-list HEAD | tail -n1
<no output>

(geo) C:\Users\basilv\code\gis-lib>git rev-list HEAD > rev.txt

(geo) C:\Users\basilv\code\gis-lib>tail rev.txt
e1d4dd7b09832e523dd62420d3c67205edaf3fba
ce5393db89dbc9e6816ca996002fbf5b9332a437
2a066f0cb199f36226d3d354aa1cc56905966f0b
564380f8b99509e098eed1033dd23f19c7f7bc38
3ea1b5eedf61ca7e90a714295e0206597ac1b44f
dddd2d7f901c23f286e33da73e1727aca1526ef5
2b5730ca3cd8b46d17fd5550af1f0a3ad26a8d9a
42da05c317dc18b3bbccf780e2ea87c53d36922e
536782336409663340331f0911dda2e6b234aa2d
8f2050756c7470e696bf2f740a92d6491a58ba54

(geo) C:\Users\basilv\code\gis-lib>tail -n1 rev.txt
<no output>
```

**Comment by toumorokoshi** [comment]
got it, thanks! super helpful.

I think assuming git rev-list works as expected, we just need to perform the `head -n 1` in python instead. https://github.com/toumorokoshi/vcver-python/blob/master/vcver/scm/git.py#L78

@basilveerman did you want to send a PR? I'll add to my queue but might be a little while.
